BEGIN;

INSERT INTO employer_monitoring_audits
  (employer_id,monitoring_tier,careers_url,ats_name,ats_url,student_source_url,
   department_source_url,research_source_url,structured_feed_url,
   association_evidence,source_confidence,coverage_status,limitations)
VALUES
(9,'A','https://karriere.hypoport.de/','Hypoport WordPress careers','https://karriere.hypoport.de/jobs/',NULL,NULL,NULL,NULL,
 'Official Hypoport careers domain identifies group companies on every vacancy.','HIGH','SUCCESS','Group-wide listing; location and employing group company must be checked per advert.'),
(10,'A','https://www.qda-solutions.com/karriere-talent-pool/','Germanedge job portal',NULL,'https://www.qda-solutions.com/karriere-talent-pool/',NULL,NULL,NULL,
 'Official QDA page names its Germanedge group portal and documents software-development internships and theses.','HIGH','PARTIAL','The group ATS target is not exposed as a stable machine-readable URL on the captured page.'),
(13,'A','https://www.mevis.fraunhofer.de/de/career-and-education.html','Fraunhofer / direct institute listing','https://www.mevis.fraunhofer.de/en/career-and-education/graduates2.html','https://www.mevis.fraunhofer.de/en/career-and-education/students.html',NULL,'https://www.mevis.fraunhofer.de/en/career-and-education/graduates2.html',NULL,
 'Official Fraunhofer MEVIS pages identify Lübeck vacancies and student routes.','HIGH','SUCCESS','Institute page mixes Bremen, Berlin and Lübeck; each vacancy location is retained.'),
(14,'A','https://www.dfki.de/web/karriere','DFKI jobs portal','https://jobs.dfki.de/ausschreibungen.html',NULL,NULL,'https://jobs.dfki.de/ausschreibungen.html',NULL,
 'jobs.dfki.de is linked from the official DFKI careers presence.','HIGH','PARTIAL','The main careers page returns HTTP 403 to the monitor; the official jobs portal remains reachable.'),
(17,'A','https://www.lhg.com/karriere','LHG jobs portal','https://jobs.lhg.com/de/jobs/iframe',NULL,NULL,NULL,NULL,
 'jobs.lhg.com is the official LHG vacancy portal and its adverts name Lübecker Hafen-Gesellschaft.','HIGH','PARTIAL','The legacy careers URL is gone; the ATS is reachable but currently exposes no relevant student software vacancy.'),
(19,'A','https://www.baader.com/about/career','BAADER custom portal','https://www.baader.com/about/career/open-positions','https://www.baader.com/about/career/your-career/student',NULL,NULL,NULL,
 'Both sources are on the official BAADER domain and link directly to BAADER job details.','HIGH','SUCCESS','Current student vacancy is production-focused; unrelated roles are classified NOT_RELEVANT.'),
(31,'A','https://career.baslerweb.com/','d.vinci / rexx-style portal','https://career.baslerweb.com/','https://career.baslerweb.com/','https://career.baslerweb.com/',NULL,NULL,
 'Official Basler careers subdomain contains vacancy details and the Students@Basler route.','HIGH','SUCCESS','Listing is HTML-only but exposes stable canonical job URLs.'),
(32,'A','https://career.xsuite.com/de','Softgarden careers','https://career.xsuite.com/de','https://career.xsuite.com/de',NULL,NULL,'https://career.xsuite.com/jobs.feed.json',
 'The official xSuite careers page declares this JSON DataFeed in schema.org metadata.','HIGH','SUCCESS','No current technical Werkstudent advert; official Young Talents signal remains monitored.'),
(46,'A','https://www.oldendorff.com/traineeships',NULL,NULL,'https://www.oldendorff.com/traineeships',NULL,NULL,NULL,
 'Official Oldendorff domain documents its early-career programs.','HIGH','PARTIAL','Former /career URL is HTTP 404 and no stable public vacancy listing was verified; traineeships only.'),
(48,'A','https://www.euroimmun.de/karriere/','EUROIMMUN careers portal','https://www.euroimmun.de/karrierebereich/jobboerse/','https://www.euroimmun.de/karriere/schueler-studenten/schueler-studentenjobs/',NULL,NULL,NULL,
 'Official EUROIMMUN pages identify the company, locations, job board and student route.','HIGH','PARTIAL','Legacy job-board URL redirects to a branded 404 response for this monitor; student page remains reachable.'),
(55,'A','https://www.possehl.digital/de/karriere','Possehl Group Personio','https://lpossehl.jobs.personio.de/?language=en',NULL,'https://www.possehl.digital/de/karriere',NULL,NULL,
 'Official Possehl Digital page links its holdings and the official Possehl group careers ecosystem.','HIGH','PARTIAL','Group ATS is broader than Possehl Digital; subsidiary association must be checked per advert.'),
(73,'A','https://www.koerber-careers.com/','SAP SuccessFactors','https://jobs.koerber.com/pharma/go/Jobs-f%C3%BCr-Studierende/4902901/', 'https://jobs.koerber.com/pharma/go/Jobs-f%C3%BCr-Studierende/4902901/',NULL,NULL,NULL,
 'Official Körber SuccessFactors portal names Körber companies on every job detail.','HIGH','SUCCESS','Group-wide student page; location and employing company are retained per advert.'),
(74,'A','https://www.otto.de/jobs/de/','OTTO corporate ATS','https://www.otto.de/jobs/de/jobsuche/werkstudent-innen/','https://www.otto.de/jobs/de/einstieg/werkstudent/',NULL,NULL,NULL,
 'Official OTTO jobs domain provides a dedicated Werkstudent search and student program page.','HIGH','SUCCESS','Search results may include nontechnical student roles, which are suppressed by relevance classification.'),
(75,'A','https://corporate.aboutyou.de/en/career','ABOUT YOU corporate careers','https://corporate.aboutyou.de/en/career/jobs',NULL,'https://corporate.aboutyou.de/en/career/tech',NULL,NULL,
 'Official ABOUT YOU corporate domain exposes canonical job pages with company, team and location.','HIGH','SUCCESS','The previously captured IT-security Werkstudent role is closed; current listing is still monitored.'),
(77,'A','https://www.statista.com/business/jobs','Ashby','https://api.ashbyhq.com/posting-api/job-board/statista',NULL,NULL,NULL,'https://api.ashbyhq.com/posting-api/job-board/statista',
 'Statista official careers page drives its live roles from the public Statista Ashby board.','HIGH','SUCCESS','ATS is third-party hosted but employer-specific and publicly exposed; no access controls are bypassed.'),
(78,'A','https://www.free-now.com/career/','Greenhouse','https://boards-api.greenhouse.io/v1/boards/freenow/jobs?content=true',NULL,NULL,NULL,'https://boards-api.greenhouse.io/v1/boards/freenow/jobs?content=true',
 'Official FREENOW job URLs use the employer-specific Greenhouse board and the API returns their canonical postings.','HIGH','PARTIAL','Official corporate pages return HTTP 429 to low-frequency direct fetches; only the public associated ATS feed is used.'),
(81,'A','https://www.nxp.com/company/about-nxp/careers:CAREERS','Workday','https://nxp.wd3.myworkdayjobs.com/wday/cxs/nxp/careers/jobs',NULL,NULL,NULL,'https://nxp.wd3.myworkdayjobs.com/wday/cxs/nxp/careers/jobs',
 'NXP official careers page links the NXP tenant on myworkdayjobs.com; the public CXS endpoint serves the same postings.','HIGH','SUCCESS','Official NXP corporate page itself returns HTTP 403; the associated Workday tenant is monitored without bypass.'),
(84,'A','https://www.rwe.com/en/rwe-careers-portal/','SAP SuccessFactors','https://jobs.rwe.com/go/All-Jobs-%28DE%29/8736501/',NULL,NULL,NULL,NULL,
 'Official RWE careers site links jobs.rwe.com and each job detail identifies the RWE employing entity.','HIGH','SUCCESS','Germany-wide listing is filtered to relevant student/technical roles and Hamburg evidence.'),
(88,'A','https://hydromapper.de/karriere','Direct official careers',NULL,'https://hydromapper.de/karriere',NULL,'https://hydromapper.de/karriere',NULL,
 'Official HydroMapper careers page contains its live vacancies, thesis route and direct application instructions.','HIGH','SUCCESS','No ATS; status depends on the single official careers page.'),
(90,'A','https://www.hcu-hamburg.de/universitaet/stellenausschreibungen','HCU public vacancies','https://www.hcu-hamburg.de/universitaet/stellenausschreibungen','https://www.hcu-hamburg.de/universitaet/stellenausschreibungen','https://www.hcu-hamburg.de/research/digital-city-science/','https://www.hcu-hamburg.de/fileadmin/documents/Research/HAWICC/NGCN/260204_Ausschreibung_SHK-WHK_HAWICC_JK.pdf',NULL,
 'Official HCU vacancy and research domains plus an HCU-hosted current student-assistant PDF.','HIGH','SUCCESS','Main vacancy page is broad; research PDF is separately monitored with explicit metadata.'),
(93,'A','https://www.desy.de/career/','DESY custom portal','https://v22.desy.de/','https://v22.desy.de/',NULL,'https://v22.desy.de/',NULL,
 'v22.desy.de is DESY’s official vacancy portal and identifies career level and Hamburg location.','HIGH','SUCCESS','Current visible student assistant role is HR-focused and therefore NOT_RELEVANT.'),
(94,'A','https://www.cml.fraunhofer.de/de/jobsundkarriere.html','Fraunhofer SuccessFactors','https://jobs.fraunhofer.de/','https://www.cml.fraunhofer.de/de/jobsundkarriere/studentische-hilfskraefte-und-praktika.html',NULL,'https://www.cml.fraunhofer.de/de/jobsundkarriere/studentische-arbeiten.html',NULL,
 'Official Fraunhofer CML pages link the Fraunhofer ATS and dedicated student routes.','HIGH','PARTIAL','Global Fraunhofer ATS cannot be safely attributed to CML without institute evidence; CML pages are monitored for links/signals.'),
(97,'A','https://jobs.kuehne-nagel.com/global/en','Kuehne+Nagel corporate ATS','https://jobs.kuehne-nagel.com/global/en',NULL,'https://jobs.kuehne-nagel.com/global/en/hamburg-it-tech-hub-jobs',NULL,NULL,
 'Official Kuehne+Nagel careers domain and Hamburg Tech Hub page identify employer and technical stack.','HIGH','PARTIAL','Global landing page is reachable but yielded no stable parseable vacancy records; irrelevant rotating page hashes are suppressed.' )
ON CONFLICT (employer_id) DO UPDATE SET
 careers_url=EXCLUDED.careers_url,ats_name=EXCLUDED.ats_name,ats_url=EXCLUDED.ats_url,
 student_source_url=EXCLUDED.student_source_url,department_source_url=EXCLUDED.department_source_url,
 research_source_url=EXCLUDED.research_source_url,structured_feed_url=EXCLUDED.structured_feed_url,
 association_evidence=EXCLUDED.association_evidence,source_confidence=EXCLUDED.source_confidence,
 coverage_status=EXCLUDED.coverage_status,limitations=EXCLUDED.limitations,updated_at=now();

INSERT INTO monitored_sources
  (employer_id,source_name,source_url,source_kind,adapter,canonical,priority_tier,
   source_priority,cadence_hours,discovery_enabled,source_confidence,association_evidence,
   monitoring_status,limitation_note,metadata)
VALUES
(9,'Hypoport official jobs','https://karriere.hypoport.de/jobs/','OFFICIAL_CAREERS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official Hypoport careers domain.','ACTIVE',NULL,'{"filter_location":"Lübeck|Hamburg|Remote|Deutschlandweit"}'),
(10,'QDA careers and talent pool','https://www.qda-solutions.com/karriere-talent-pool/','OFFICIAL_STUDENT_PAGE','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official QDA page.','LIMITED','Page documents routes but the linked group ATS is not stable.','{"default_location":"Lübeck"}'),
(13,'MEVIS official vacancies','https://www.mevis.fraunhofer.de/en/career-and-education/graduates2.html','OFFICIAL_INSTITUTE_PAGE','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official Fraunhofer MEVIS page.','ACTIVE',NULL,'{"filter_location":"Lübeck","default_location":"Lübeck"}'),
(13,'MEVIS student routes','https://www.mevis.fraunhofer.de/en/career-and-education/students.html','OFFICIAL_STUDENT_PAGE','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official Fraunhofer MEVIS page.','ACTIVE',NULL,'{"filter_location":"Lübeck","default_location":"Lübeck"}'),
(14,'DFKI official vacancies','https://jobs.dfki.de/ausschreibungen.html','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official DFKI jobs portal.','LIMITED','Main DFKI careers page is HTTP 403.','{"filter_location":"Lübeck|Remote","default_location":"Lübeck"}'),
(17,'LHG official jobs','https://jobs.lhg.com/de/jobs/iframe','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official LHG jobs subdomain.','ACTIVE',NULL,'{"default_location":"Lübeck"}'),
(19,'BAADER official job portal','https://www.baader.com/about/career/open-positions','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official BAADER domain.','ACTIVE',NULL,'{"filter_location":"Lübeck","default_location":"Lübeck"}'),
(19,'BAADER student routes','https://www.baader.com/about/career/your-career/student','OFFICIAL_STUDENT_PAGE','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official BAADER domain.','ACTIVE',NULL,'{"default_location":"Lübeck"}'),
(31,'Basler official jobs','https://career.baslerweb.com/','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official Basler careers subdomain.','ACTIVE',NULL,'{"default_location":"Ahrensburg"}'),
(32,'xSuite declared JSON job feed','https://career.xsuite.com/jobs.feed.json','OFFICIAL_ATS','schema_datafeed',TRUE,'A',1,12,TRUE,'HIGH','Declared by schema.org metadata on official xSuite careers page.','ACTIVE',NULL,'{"filter_location":"Ahrensburg|Hamburg|Remote|Deutschland"}'),
(32,'xSuite Young Talents page','https://career.xsuite.com/de','OFFICIAL_STUDENT_PAGE','career_page',TRUE,'A',2,24,FALSE,'HIGH','Official xSuite careers page.','ACTIVE',NULL,'{}'),
(46,'Oldendorff traineeships','https://www.oldendorff.com/traineeships','OFFICIAL_STUDENT_PAGE','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official Oldendorff domain.','LIMITED','No stable public vacancy list verified.','{"default_location":"Lübeck"}'),
(48,'EUROIMMUN job board','https://www.euroimmun.de/karrierebereich/jobboerse/','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official EUROIMMUN domain.','UNMONITORABLE','Currently resolves to a branded 404 page.','{"filter_location":"Lübeck|Dassow|Selmsdorf|Groß Grönau"}'),
(48,'EUROIMMUN student jobs','https://www.euroimmun.de/karriere/schueler-studenten/schueler-studentenjobs/','OFFICIAL_STUDENT_PAGE','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official EUROIMMUN domain.','ACTIVE',NULL,'{"default_location":"Lübeck"}'),
(55,'Possehl Digital careers','https://www.possehl.digital/de/karriere','OFFICIAL_CAREERS','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official Possehl Digital domain.','LIMITED','Mostly routes to group subsidiaries.','{"default_location":"Lübeck"}'),
(55,'Possehl Group Personio','https://lpossehl.jobs.personio.de/?language=en','OFFICIAL_ATS','personio_list',FALSE,'A',2,12,TRUE,'HIGH','Official Possehl group ATS linked from group careers.','LIMITED','Broader group source; employing company must be checked.','{"filter_location":"Lübeck"}'),
(73,'Körber student jobs','https://jobs.koerber.com/pharma/go/Jobs-f%C3%BCr-Studierende/4902901/','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,8,TRUE,'HIGH','Official Körber SuccessFactors portal.','ACTIVE',NULL,'{"filter_location":"Hamburg","default_location":"Hamburg"}'),
(74,'OTTO Werkstudent search','https://www.otto.de/jobs/de/jobsuche/werkstudent-innen/','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,8,TRUE,'HIGH','Official OTTO jobs search.','ACTIVE',NULL,'{"filter_location":"Hamburg","default_location":"Hamburg"}'),
(74,'OTTO Werkstudent program','https://www.otto.de/jobs/de/einstieg/werkstudent/','OFFICIAL_STUDENT_PAGE','career_page',TRUE,'A',2,24,FALSE,'HIGH','Official OTTO student page.','ACTIVE',NULL,'{}'),
(75,'ABOUT YOU official jobs','https://corporate.aboutyou.de/en/career/jobs','OFFICIAL_CAREERS','generic_official_list',TRUE,'A',1,8,TRUE,'HIGH','Official ABOUT YOU corporate domain.','ACTIVE',NULL,'{"filter_location":"Hamburg|Hamburg or Berlin","default_location":"Hamburg"}'),
(77,'Statista public Ashby board','https://api.ashbyhq.com/posting-api/job-board/statista','OFFICIAL_ATS','ashby_feed',TRUE,'A',1,8,TRUE,'HIGH','Employer-specific ATS behind official Statista careers.','ACTIVE',NULL,'{"filter_location":"Hamburg|Germany|Remote"}'),
(78,'FREENOW public Greenhouse board','https://boards-api.greenhouse.io/v1/boards/freenow/jobs?content=true','OFFICIAL_ATS','greenhouse_feed',TRUE,'A',1,8,TRUE,'HIGH','Employer-specific ATS matching official FREENOW job URLs.','LIMITED','Corporate careers page returns HTTP 429.','{"filter_location":"Hamburg|Remote"}'),
(78,'FREENOW corporate careers','https://www.free-now.com/career/jobs/','OFFICIAL_CAREERS','career_page',TRUE,'A',3,24,FALSE,'HIGH','Official FREENOW domain.','UNMONITORABLE','HTTP 429 access restriction; retained to log failure.','{}'),
(81,'NXP Workday public CXS','https://nxp.wd3.myworkdayjobs.com/wday/cxs/nxp/careers/jobs','OFFICIAL_ATS','workday_feed',TRUE,'A',1,8,TRUE,'HIGH','Official NXP Workday tenant.','ACTIVE',NULL,'{"method":"POST","body":{"appliedFacets":{},"limit":20,"offset":0,"searchText":"Working Student Hamburg"},"filter_location":"Hamburg","detail_base":"https://nxp.wd3.myworkdayjobs.com/en-US/careers"}'),
(84,'RWE Germany jobs','https://jobs.rwe.com/go/All-Jobs-%28DE%29/8736501/','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,8,TRUE,'HIGH','Official RWE SuccessFactors portal.','ACTIVE',NULL,'{"filter_location":"Hamburg","default_location":"Hamburg","suppress_page_change":true}'),
(84,'RWE Asset Risk student role','https://jobs.rwe.com/RWE/job/Hamburg-Working-Student-Asset-Risk-and-Lifetime-Optimization-dfm-HH-20354/1423493033/','OFFICIAL_JOB_DETAIL','job_detail',TRUE,'A',1,8,FALSE,'HIGH','Current official RWE SuccessFactors detail.','ACTIVE',NULL,'{}'),
(88,'HydroMapper careers','https://hydromapper.de/karriere','OFFICIAL_CAREERS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official HydroMapper domain.','ACTIVE',NULL,'{"default_location":"Hamburg"}'),
(88,'HydroMapper geoinformatics thesis route','https://hydromapper.de/karriere#abschlussarbeiten','OFFICIAL_RESOURCE','static_job_resource',TRUE,'A',1,12,FALSE,'HIGH','Current route stated on official HydroMapper careers page.','ACTIVE',NULL,'{"title":"Abschlussarbeiten im Bereich Vermessung, Geodäsie, Geoinformatik oder Geomatik","location":"Hamburg","opportunity_type":"Thesis","employment_type":"Student","enrollment_requirement":"Bachelor or Master thesis route; exact enrollment terms not stated","language_bucket":"NO_GERMAN_THRESHOLD_STATED","technologies":["GIS"],"description":"Official HydroMapper thesis route in geodesy and geoinformatics. The company develops software and high-precision 3D infrastructure data; exact thesis topic and programming requirements are not stated."}'),
(90,'HCU vacancies','https://www.hcu-hamburg.de/universitaet/stellenausschreibungen','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official HCU domain.','ACTIVE',NULL,'{"default_location":"Hamburg"}'),
(90,'HCU HAWICC student-assistant PDF','https://www.hcu-hamburg.de/fileadmin/documents/Research/HAWICC/NGCN/260204_Ausschreibung_SHK-WHK_HAWICC_JK.pdf','OFFICIAL_RESOURCE','static_job_resource',TRUE,'A',1,12,FALSE,'HIGH','Official HCU-hosted current vacancy PDF.','ACTIVE',NULL,'{"title":"Studentische/Wissenschaftliche Hilfskraft – HAWICC","location":"Hamburg","opportunity_type":"Student Assistant","employment_type":"Student / part-time","enrollment_requirement":"Eingeschriebene:r Student:in an der HCU","language_bucket":"GERMAN_REQUIRED_UNSPECIFIED_LEVEL","technologies":["AI"],"description":"HAWICC student-assistant support for research and project work concerning wireless technologies, artificial intelligence and sustainability; official HCU PDF."}'),
(93,'DESY official vacancies','https://v22.desy.de/','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official DESY vacancy portal.','ACTIVE',NULL,'{"filter_location":"Hamburg","default_location":"Hamburg"}'),
(94,'Fraunhofer CML student roles','https://www.cml.fraunhofer.de/de/jobsundkarriere/studentische-hilfskraefte-und-praktika.html','OFFICIAL_STUDENT_PAGE','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official Fraunhofer CML page.','LIMITED','Links may point into global Fraunhofer ATS; CML association required.','{"default_location":"Hamburg"}'),
(94,'Fraunhofer CML student research','https://www.cml.fraunhofer.de/de/jobsundkarriere/studentische-arbeiten.html','OFFICIAL_STUDENT_PAGE','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official Fraunhofer CML page.','ACTIVE',NULL,'{"default_location":"Hamburg"}'),
(97,'Kuehne+Nagel official jobs','https://jobs.kuehne-nagel.com/global/en','OFFICIAL_ATS','generic_official_list',TRUE,'A',1,12,TRUE,'HIGH','Official Kuehne+Nagel careers domain.','LIMITED','No stable parseable vacancy records in direct HTML.','{"filter_location":"Hamburg","default_location":"Hamburg","suppress_page_change":true}'),
(97,'Kuehne+Nagel Hamburg Tech Hub','https://jobs.kuehne-nagel.com/global/en/hamburg-it-tech-hub-jobs','OFFICIAL_CAREERS','generic_official_list',TRUE,'A',2,24,TRUE,'HIGH','Official employer department page.','LIMITED','Department page is evidence-rich but not a vacancy feed.','{"default_location":"Hamburg","suppress_page_change":true}')
ON CONFLICT (source_url) DO UPDATE SET
 employer_id=EXCLUDED.employer_id,source_name=EXCLUDED.source_name,source_kind=EXCLUDED.source_kind,
 adapter=EXCLUDED.adapter,canonical=EXCLUDED.canonical,priority_tier='A',source_priority=EXCLUDED.source_priority,
 cadence_hours=EXCLUDED.cadence_hours,enabled=TRUE,discovery_enabled=EXCLUDED.discovery_enabled,
 source_confidence=EXCLUDED.source_confidence,association_evidence=EXCLUDED.association_evidence,
 monitoring_status=EXCLUDED.monitoring_status,limitation_note=EXCLUDED.limitation_note,
 metadata=EXCLUDED.metadata,updated_at=now();

COMMIT;
