BEGIN;

INSERT INTO opportunities (
  employer_id, title, location, opportunity_type, role_family, status,
  language_requirement, work_model, technology_mentions, job_url,
  source_date, verified_at, relevance_note
)
SELECT employer_id, v.title, v.location, v.opportunity_type, v.role_family,
       v.status, v.language_requirement, v.work_model, v.technology_mentions,
       v.job_url, v.source_date, DATE '2026-08-30', v.relevance_note
FROM employers e
JOIN (VALUES
 ('Drägerwerk AG & Co. KGaA','Werkstudent Software Development','Lübeck','Werkstudent','Software Engineering','LIVE','German ad; no CEFR stated','Part-time / mobile work possible',ARRAY['Python','Automated Testing','Hardware-in-the-loop']::TEXT[],'https://erecruitment.draeger.com/index.php?ac=jobad&id=19484&language=1',DATE '2026-08-30','Top local opportunity; tailor around Python, production debugging and test automation.'),
 ('Fraunhofer IMTE','Studentische Hilfskraft Frontend-Entwicklung & UX-Design für Medizintechnik','Lübeck','Student Assistant','Frontend / Full Stack','LIVE','No explicit CEFR captured','Flexible hours; device work likely onsite',ARRAY['React','TypeScript','REST','gRPC','SQLite','Python','C++','Julia']::TEXT[],'https://jobs.fraunhofer.de/job/L%C3%BCbeck-Studentische-Hilfskraft-Frontend-Entwicklung-%26-UX-Design-f%C3%BCr-Medizintechnik-%28all-genders%29-23562/1430796633/',DATE '2026-08-27','Best exact-stack local role; apply immediately with React/TypeScript/API examples.'),
 ('singularIT GmbH','Back-End Software Developer:in — Werkstudium','Lübeck','Werkstudent','Backend','LIVE','German recruitment page; CEFR not stated','Unknown',ARRAY['Backend','Web','Data']::TEXT[],'https://www.singular-it.de/jobs',DATE '2026-08-30','Small local software firm; emphasize paid backend and database delivery.'),
 ('Shinefour GmbH','Werkstudent Softwareentwicklung','Lübeck','Werkstudent','Software Engineering','LIVE','German ad; CEFR not stated','Hybrid / home-office possibilities',ARRAY['Java','Spring Boot','SQL','Git']::TEXT[],'https://de.indeed.com/viewjob?jk=8b4f5c1086846702',DATE '2026-05-30','Strong SQL/backend transfer; address the Java gap proactively.'),
 ('Kontor Business IT GmbH','Werkstudierende Support / Beratung','Lübeck','Werkstudent','Technical Support / Security','LIVE','Strong German likely due customer support','Onsite / unknown hybrid',ARRAY['IT Infrastructure','IT Security','Web']::TEXT[],'https://kbit.de/karriere',DATE '2026-08-30','Useful fast-entry route; security studies are explicitly accepted.'),
 ('Stadtwerke Lübeck Digital GmbH','Werkstudent:in Helpdesk Digitale Schule','Lübeck','Werkstudent','Technical Support','LIVE','German C1 explicitly required','Onsite school IT support',ARRAY['Ticketing','Knowledge Base','School IT']::TEXT[],'https://stellenangebote.swhl.de/Werkstudentin-Helpdesk-Digitale-Schule-de-j1638.html',DATE '2026-08-30','Do not prioritize until German approaches C1; keep as language benchmark.'),
 ('VisiConsult X-ray Systems & Solutions GmbH','Unsolicited application — Students','Stockelsdorf','Student / Internship','Software / Data / Automation','LIVE','Good German and English requested','Flexible hours',ARRAY['Software Development','AI','Imaging','Automation']::TEXT[],'https://visiconsult-x-ray-systems-solutions-gmbh.jobs.personio.de/job/449656?language=en',DATE '2026-08-30','Submit a targeted student application around data pipelines, imaging data and backend automation.'),
 ('VisiConsult X-ray Systems & Solutions GmbH','Master thesis — X-ray image filtering/compression','Stockelsdorf','Thesis','Data / Imaging','LIVE','Good German and English preferred','Onsite / flexible',ARRAY['Image Processing','Data Compression']::TEXT[],'https://visiconsult-x-ray-systems-solutions-gmbh.jobs.personio.de/?language=en',DATE '2026-08-30','Adjacent rather than exact; useful evidence that technical students are actively integrated.'),
 ('Basler AG','Praktikum oder Werkstudierendentätigkeit in der Forschung: Vermessung von Bildgebungskomponenten','Ahrensburg','Werkstudent / Internship','Research / Imaging','LIVE','Role-specific requirement not captured','Mix Office & Remote may vary',ARRAY['Computer Vision','Imaging']::TEXT[],'https://career.baslerweb.com/',DATE '2026-08-30','Apply if willing to pivot toward computer vision and imaging systems.'),
 ('embeff GmbH','Werkstudent Embedded Software','Lübeck','Werkstudent','Embedded / Test Automation','LIVE','German ad; CEFR not stated','Unknown',ARRAY['Embedded','Microcontrollers','Drivers','Test Automation']::TEXT[],'https://www.iti.uni-luebeck.de/fileadmin/Ausschreibungen/WerkstudentIn_EmbeddedSoftware.pdf',DATE '2026-02-28','Niche startup role; position existing testing/debugging skills as transferable.'),
 ('Obungi GmbH','Werkstudent IT Projektmanagement','Hamburg / Bremen / Lübeck','Werkstudent','Technical Project Management','LIVE','German client context likely','Partially remote',ARRAY['Cloud','Data','Analytics','AI']::TEXT[],'https://www.stepstone.de/jobs/werkstudent-it/in-l%C3%BCbeck',DATE '2026-08-16','Not coding-first, but explicitly Lübeck-compatible and close to data/cloud delivery.'),
 ('ABOUT YOU SE & Co. KG','Working Student — IT-Security','Hamburg','Working Student','IT Security','LIVE','Check official posting','Hybrid',ARRAY['IT Security','Application Security']::TEXT[],'https://jobs.smartrecruiters.com/ABOUTYOUGmbH/744000134485449-working-student-it-security-all-genders-',DATE '2026-08-01','Direct bridge from web/backend evidence into the MSc security direction.'),
 ('NXP Semiconductors Germany GmbH','Working Student AI Automation Engineer — Quality Automation','Hamburg','Working Student','AI / QA Automation','LIVE','English/global team; exact German requirement to verify','Unknown',ARRAY['AI','Python','Automation','Quality']::TEXT[],'https://www.tuhh.de/t3resources/tuhh/download/universitaet/cc/Career_Forum/Unternehmensstelleangebote/R-10054774_Working_Student_AI_Automation_Engineer_Quality_Automation.pdf',DATE '2026-04-30','Use Python automation, debugging and deployment evidence.'),
 ('Airbus Operations GmbH','Werkstudent Cyber Security (d/f/m)','Hamburg Area','Werkstudent','Cybersecurity','LIVE','Role-specific; global team','Unknown',ARRAY['Cybersecurity','Consulting']::TEXT[],'https://ag.wd3.myworkdayjobs.com/de-DE/Airbus/job/Hamburg-Area/Werkstudent-im-Bereich-Cyber-Security---D-F-M-_JR10407766?locationCountry=dcc5b7608d8644b3a93716604e78e995',DATE '2026-08-01','Apply opportunistically; commute and competition make it secondary to Lübeck roles.'),
 ('CGI Deutschland B.V. & Co. KG','Werkstudent Cybersecurity Team','Hamburg','Werkstudent','Cybersecurity','LIVE','German client context likely','Hybrid',ARRAY['Cybersecurity','IT Consulting']::TEXT[],'https://cgi.njoyn.com/corp/xweb/xweb.asp?BRID=1312300&Jobid=J0626-2551&NTKN=c&Page=JobDetails&clid=21001&lang=4',DATE '2026-06-30','Credible software-to-security bridge; emphasize secure backend and client delivery.'),
 ('RWE Renewables Europe & Australia GmbH','Working Student Engineering GIS','Hamburg','Working Student','GIS / Digital Transformation','LIVE','Excellent German and English explicitly required','Hybrid',ARRAY['GIS','ERP','SCADA','Analytics','Spatial Data']::TEXT[],'https://www.xing.com/jobs/hamburg-working-student-engineering-gis-152334435',DATE '2026-03-30','Technically excellent but language-blocked; only apply if German improves faster than expected.'),
 ('HanseCom Public Transport Ticketing Solutions GmbH','Werkstudent Geoinformatik / Informatik','Hamburg','Werkstudent','GIS / Mobility Software','LIVE','German ad; verify exact requirement','Hybrid',ARRAY['GIS','Geodata','Spatial Databases','Movement Data']::TEXT[],'https://init-portal-hansecom.rexx-systems.com/Werkstudent-mwd-Geoinformatik-Informatik-de-j1157.html',DATE '2026-08-16','Highest-priority Hamburg niche role; lead with PostGIS optimization and Chargerzilla maps.'),
 ('STF Gruppe GmbH','Werkstudent Netzplanung / Geograph / Geomatik','Hamburg','Werkstudent','GIS / Infrastructure','LIVE','Sufficient German explicitly required','Unknown',ARRAY['GIS','Network Planning','3D Scanning']::TEXT[],'https://stf-gruppe.softgarden.io/job/66556103?l=de',DATE '2026-08-20','Fresh niche role but German requirement is a real screen.'),
 ('Dr. Hesse und Partner Ingenieure','Evergreen Werkstudent pathway — Geodesy / Geoinformatics','Hamburg','Werkstudent','Geospatial','LIVE','German page; exact CEFR not stated','Onsite / field work possible',ARRAY['3D Scanning','Data Evaluation','Monitoring']::TEXT[],'https://dhpi.com/de/karriere/werkstudenten',DATE '2026-08-30','Use as a direct speculative application; specialist employer may value niche evidence.')
) AS v(company_name,title,location,opportunity_type,role_family,status,language_requirement,work_model,technology_mentions,job_url,source_date,relevance_note)
ON e.company_name = v.company_name
ON CONFLICT (employer_id, title, job_url) DO UPDATE SET
  status = EXCLUDED.status,
  verified_at = EXCLUDED.verified_at,
  relevance_note = EXCLUDED.relevance_note;

COMMIT;
