BEGIN;
DELETE FROM university_units WHERE institution='Universität zu Lübeck';
INSERT INTO university_units(institution,unit_name,unit_type,research_focus,relevant_work,
 technologies,student_route,current_opportunity,language_evidence,official_url,priority,status,checked_at) VALUES
('Universität zu Lübeck','Institut für IT-Sicherheit (ITS)','Institute',
 'Cybersecurity and trustworthy systems.','Security research, secure software/systems, research programming.',
 ARRAY['security','trustworthy systems'],
 'Approach research groups after enrollment; central institute list is verified but no current HiWi advert was located.',NULL,
 'Do not infer English from the website; confirm with the group.','https://www.its.uni-luebeck.de/','HIGH','NEEDS_RESEARCH','2026-08-30'),
('Universität zu Lübeck','Institut für Softwaretechnik und Programmiersprachen (ISP)','Institute',
 'Software engineering, programming languages and software verification.','Research software, testing, verification and tooling.',
 ARRAY['software engineering','programming languages','verification'],
 'Contact project/group leads and watch institute pages; no exact current HiWi advert verified.',NULL,
 'Some research material is international, but role language must be checked.','https://www.isp.uni-luebeck.de/','HIGH','NEEDS_RESEARCH','2026-08-30'),
('Universität zu Lübeck','Institut für Technische Informatik (ITI)','Institute / labs',
 'Computer engineering, trustworthy hardware, embedded systems and intelligent systems.','Secure processor work, Industrial IoT software, deployment and testing.',
 ARRAY['RISC-V','Java','Industrial IoT','Arrowhead Tools'],
 'Direct e-mail to named researchers; institute has formal HiWi administration.',
 'Two verified live routes: secure RISC-V processor and Intelligent Systems Lab / Arrowhead Tools HiWi.',
 'Both opportunities are published in English; no German CEFR requirement stated.',
 'https://www.iti.uni-luebeck.de/studiiti/hilfskraefte.html','HIGH','VERIFIED','2026-08-30'),
('Universität zu Lübeck','Institut für Telematik (ITM)','Institute',
 'Networks, distributed systems, Internet of Things and smart-city/medical applications.',
 'Distributed/backend systems, network research, IoT prototypes and research software.',
 ARRAY['distributed systems','networks','IoT'],
 'Ongoing project/thesis topics indicate a route to project teams; ask supervisors about paid HiWi funding.',NULL,
 'Role language is not evidenced; confirm per group.',
 'https://www.itm.uni-luebeck.de/','HIGH','VERIFIED','2026-08-30'),
('Universität zu Lübeck','Institut für Informationssysteme (IFIS)','Institute',
 'Information systems, knowledge representation, efficient storage/querying and inference over large data.',
 'Database/data engineering, knowledge systems and research prototypes.',
 ARRAY['databases','query processing','knowledge representation','large data'],
 'Targeted approach is justified by exact database fit; current paid opening was not verified.',NULL,
 'No role-level language evidence.',
 'https://www.ifis.uni-luebeck.de/','HIGH','NEEDS_RESEARCH','2026-08-30'),
('Universität zu Lübeck','Institut für Medizinische Informatik (IMI)','Institute',
 'Medical informatics, clinical data and digital-health systems.',
 'Health-data processing, research software, interoperability and analytics.',
 ARRAY['medical informatics','health data','software'],
 'Contact active project groups after enrollment; no exact current HiWi advert verified.',NULL,
 'No role-level language evidence.',
 'https://www.imi.uni-luebeck.de/','HIGH','NEEDS_RESEARCH','2026-08-30'),
('Universität zu Lübeck','Institut für Multimediale und Interaktive Systeme (IMIS)','Institute',
 'Human-computer interaction, interactive systems and usable digital products.',
 'Frontend/prototyping, UX research, web/mobile interfaces and software studies.',
 ARRAY['interactive systems','HCI','frontend','UX'],
 'Ask project leads about research-programming or tutor roles; no exact current vacancy verified.',NULL,
 'No role-level language evidence.',
 'https://www.imis.uni-luebeck.de/','MEDIUM','NEEDS_RESEARCH','2026-08-30'),
('Universität zu Lübeck','Institut für Neuro- und Bioinformatik (INB)','Institute',
 'Machine learning, neural/bioinformatics and computational data analysis.',
 'Python/data/ML research tooling and teaching support.',
 ARRAY['machine learning','bioinformatics','data analysis'],
 'The institute publishes current 2026/27 HiWi hiring paperwork, proving active HiWi administration; ask groups for funded tasks.',NULL,
 'No role-level language evidence.',
 'https://www.inb.uni-luebeck.de/hiwis-mitarbeit-am-inb','HIGH','VERIFIED','2026-08-30'),
('Universität zu Lübeck','Institut für Robotik und Kognitive Systeme (ROB)','Institute',
 'Robotics, autonomous/cognitive systems and perception.','Robot software, sensing, simulation and research tooling.',
 ARRAY['robotics','autonomous systems','perception'],
 'Investigate project pages and contact researchers; no exact current HiWi advert verified.',NULL,
 'No role-level language evidence.','https://www.rob.uni-luebeck.de/','MEDIUM','NEEDS_RESEARCH','2026-08-30'),
('Universität zu Lübeck','Institute of Mathematics and Image Computing (MIC)','Institute',
 'Medical image computing, inverse problems and image/data analysis.','Python/C++ research software, imaging pipelines and numerical/data work.',
 ARRAY['medical imaging','image processing','data analysis'],
 'Approach project leads; current paid student opening not verified.',NULL,
 'International research context is not sufficient to claim a role language.',
 'https://www.mic.uni-luebeck.de/','HIGH','NEEDS_RESEARCH','2026-08-30'),
('Universität zu Lübeck','Institut für Signalverarbeitung (ISIP)','Institute',
 'Signal processing and data-driven sensing.','Scientific programming, data pipelines, experiments and simulation.',
 ARRAY['signal processing','scientific computing'],
 'Institute maintains HiWi employment documents, showing the route exists; ask for funded projects.',NULL,
 'No role-level language evidence.','https://www.isip.uni-luebeck.de/','MEDIUM','VERIFIED','2026-08-30'),
('Universität zu Lübeck','Institut für Theoretische Informatik (TCS)','Institute',
 'Algorithms and theoretical computer science.','Tutoring, algorithms and software supporting research projects.',
 ARRAY['algorithms','theoretical computer science'],
 'Official page says tutors are recruited every semester, research projects frequently have roles, and informal applications are welcome.',
 'Recurring tutor/HiWi and speculative project route; no single titled vacancy.',
 'Informal route exists, but working language must be confirmed.',
 'https://www.tcs.uni-luebeck.de/de/institut/stellen/','HIGH','VERIFIED','2026-08-30'),
('Universität zu Lübeck','Zentrum für Künstliche Intelligenz Lübeck (ZKIL)','Cross-institute center',
 'Interdisciplinary AI across medical informatics, telematics, software engineering and other institutes.',
 'Applied AI, data pipelines, model tooling and cross-institute research software.',
 ARRAY['AI','machine learning','data'],
 'Use the center to identify funded projects and then approach the responsible institute; no central student vacancy verified.',NULL,
 'Cross-institute international activity does not prove role language.',
 'https://research.uni-luebeck.de/de/organisations/center-for-artificial-intelligence-luebeck-zkil/','HIGH','VERIFIED','2026-08-30'),
('Universität zu Lübeck','IT-Service-Center (ITSC)','Central technical service',
 'University infrastructure and IT services.','Systems, identity/access, support, infrastructure and security operations.',
 ARRAY['IT infrastructure','identity','support','security operations'],
 'Watch university vacancies and ask after enrollment; no exact current student role verified.',NULL,
 'German is likely operationally important, but this remains an inference until a role states it.',
 'https://www.itsc.uni-luebeck.de/','MEDIUM','NEEDS_RESEARCH','2026-08-30');
COMMIT;
