import { Database, HardDrive, RadioTower, Server, ShieldCheck } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Badge, Card, SectionError, StatusDot } from "@/components/ui";
import { bytes, exactTime, relativeTime } from "@/lib/format";
import { getSystem } from "@/lib/queries";

export default async function SystemPage() {
  const system = await getSystem(); const source = system.sources.data[0]; const db = system.database.data[0]; const backup = system.backups.data[0]; const lastS = system.runs.data.find((run) => run.requested_tiers.includes("S")); const lastA = system.runs.data.find((run) => run.requested_tiers.includes("A")); const diskUsed = system.runtime.diskTotal ? Math.round(100 * (system.runtime.diskTotal - system.runtime.diskFree) / system.runtime.diskTotal) : null;
  const facts = [["Server", "Dashboard online", "healthy", Server], ["PostgreSQL", db ? `PostgreSQL ${db.version} · ${bytes(Number(db.bytes))}` : "Unavailable", db ? "healthy" : "down", Database], ["Scheduler", lastS && lastA ? "Monitoring runs are being recorded" : "Run freshness unavailable", lastS && lastA ? "healthy" : "degraded", RadioTower], ["Alert engine", system.alerts.error ? "Unavailable" : `Last alert ${relativeTime(system.alerts.data[0]?.last_created)}`, system.alerts.error ? "down" : "healthy", ShieldCheck], ["Disk usage", diskUsed == null ? "Unavailable" : `${diskUsed}% used · ${bytes(system.runtime.diskFree)} free`, diskUsed == null ? "degraded" : diskUsed >= 90 ? "down" : diskUsed >= 80 ? "degraded" : "healthy", HardDrive]] as const;
  return <><PageHeader title="System" subtitle="Read-only operational overview" updatedAt={system.checkedAt} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{facts.map(([name, detail, status, Icon]) => <Card key={name} className="p-5"><div className="flex items-center justify-between"><Icon className="size-4 text-slate-400" /><StatusDot status={status} /></div><p className="mt-5 text-sm font-semibold text-slate-900">{name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></Card>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><Card className="p-6"><p className="text-sm font-semibold text-slate-900">Operations</p><dl className="mt-5 divide-y divide-[var(--border)]">{[["Last S run", lastS ? `${relativeTime(lastS.finished_at)} · ${lastS.status}` : "—"], ["Last A run", lastA ? `${relativeTime(lastA.finished_at)} · ${lastA.status}` : "—"], ["Latest backup", backup ? `${relativeTime(backup.completed_at)} · ${backup.status}` : "—"], ["Restore verification", backup?.restore_verified_at ? exactTime(backup.restore_verified_at) : "No verified restore recorded"], ["Daily digest", relativeTime(system.digest.data[0]?.generated_at)], ["Enabled sources", source?.enabled?.toString() || "—"]].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-5 py-3 text-sm"><dt className="text-slate-500">{label}</dt><dd className="text-right font-medium text-slate-800">{value}</dd></div>)}</dl></Card>
      <Card className="p-6"><p className="text-sm font-semibold text-slate-900">Recent monitor runs</p>{system.runs.error ? <div className="mt-4"><SectionError /></div> : <div className="mt-4 divide-y divide-[var(--border)]">{system.runs.data.slice(0, 8).map((run) => <div key={run.run_id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium text-slate-800">{run.requested_tiers.join(" + ")} monitor</p><p className="mt-0.5 text-xs text-slate-400">{exactTime(run.finished_at)} · {run.sources_succeeded}/{run.sources_attempted} sources</p></div><Badge tone={run.status === "SUCCEEDED" ? "green" : run.status === "FAILED" ? "red" : "amber"}>{run.status}</Badge></div>)}</div>}</Card></div>
    <p className="mt-5 text-xs text-slate-400">No server-control actions, credentials, environment values, or raw logs are exposed.</p>
  </>;
}
