import { ExternalLink } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Badge, Card, EmptyState, SectionError } from "@/components/ui";
import { exactTime, relativeTime } from "@/lib/format";
import { getSources } from "@/lib/queries";

export default async function SourcesPage() {
  const result = await getSources(); const repeated = result.data.filter((source) => source.consecutive_errors >= 3).length;
  return <><PageHeader title="Sources" subtitle={`${result.data.length || "—"} enabled sources · ${repeated} need attention`} /><Card className="overflow-hidden"><div className="hidden grid-cols-[1.1fr_1.5fr_.4fr_.6fr_.8fr_.8fr_.4fr] gap-4 border-b border-[var(--border)] bg-slate-50/70 px-6 py-3 text-[11px] font-semibold uppercase tracking-wider text-slate-400 md:grid"><span>Employer</span><span>Source</span><span>Tier</span><span>Status</span><span>Last checked</span><span>Last success</span><span>Failures</span></div>{result.error ? <div className="p-6"><SectionError /></div> : !result.data.length ? <div className="p-6"><EmptyState title="No sources" detail="No enabled monitored sources were found." /></div> : <div className="divide-y divide-[var(--border)]">{result.data.map((source) => { const unhealthy = source.consecutive_errors > 0; return <div key={source.monitored_source_id} className={`grid gap-2 px-5 py-4 text-sm md:grid-cols-[1.1fr_1.5fr_.4fr_.6fr_.8fr_.8fr_.4fr] md:items-center md:gap-4 md:px-6 ${source.consecutive_errors >= 3 ? "bg-amber-50/35" : ""}`}><span className="font-medium text-slate-900">{source.company_name}</span><a href={source.source_url} target="_blank" rel="noreferrer" className="flex min-w-0 items-center gap-1.5 truncate text-slate-600 hover:text-[var(--accent)]">{source.source_name}<ExternalLink className="size-3 shrink-0" /></a><span><Badge>{source.priority_tier}</Badge></span><span><Badge tone={unhealthy ? "amber" : "green"}>{unhealthy ? "Attention" : "Healthy"}</Badge></span><span className="text-xs text-slate-500" title={exactTime(source.last_checked_at)}>{relativeTime(source.last_checked_at)}</span><span className="text-xs text-slate-500" title={exactTime(source.last_success_at)}>{relativeTime(source.last_success_at)}</span><span className={`text-xs font-semibold ${unhealthy ? "text-amber-700" : "text-slate-400"}`}>{source.consecutive_errors}</span></div>; })}</div>}</Card></>;
}
